.. py:exception:: ApiError


   Bases: :py:obj:`RuntimeError`

   
   Unspecified run-time error.
















   ..
       !! processed by numpydoc !!
